const main = {
  id: {
    texts: {
      loading: "Loading assets..",
      welcome: "Selamat Datang di Portofolio,",
      explore: "Jelajahi Sekarang",
      subtitle: "Web Developer",
      motto: "Ikhtiar dulu, masalah hasil sudah ada yang mengatur.",
      back: "Kembali",
      "nav-about": "Tentang",
      "nav-experience": "Pengalaman",
      "nav-competency": "Kompetensi",
      "nav-project": "Project",
      "download-cv": "Download CV",
      "scroll-down": "Scroll Down",
      "title-experience": "Pengalaman",
      "title-competency": "Kompetensi",
      "title-project": "Project",
      "nav-view-all": "Lihat Semua",
    },
    tentang: [
      `Perjalanan saya dimulai pada tahun <span class="text-white font-bold">2018 (SMA)</span>, saat sebuah perkenalan sederhana dengan bahasa Pascal memicu ketertarikan mendalam saya pada dunia IT. Melalui komunitas <span class="text-white font-bold">CLUTIK</span>, saya belajar bahwa teknologi bukan hanya soal instruksi mesin, tapi tentang seni memecahkan masalah.`,
      `Berbekal semangat tersebut, kini saya aktif mengembangkan solusi perangkat lunak untuk <span class="text-white font-bold">perorangan hingga perusahaan berskala besar</span>. Bagi saya, setiap proyek adalah <span class="text-white font-bold">permainan <span class="italic">problem-solving</span></span> jangka panjang yang selalu memotivasi saya untuk keluar dari zona nyaman.`,
    ],
    pengalaman: [
      {
        tahun: "2018 - 2020",
        link: "https://sman2mojokerto.sch.id/ekskul/club-tik-clutik/",
        title: "Club TIK (Clutik) di SMAN 2 Mojokerto",
        desc: "Melalui ekstrakurikuler CLUTIK, saya menemukan minat awal di dunia IT. Di sini, saya membangun fondasi teknis melalui pemrograman bahasa Pascal serta penguasaan perangkat keras, mulai dari pemahaman komponen hingga proses perakitan komputer.",
        detil: [
          "Merakit Komputer",
          "Sistem Operasi Komputer",
          "Jaringan Komputer",
          "Dasar Pemrograman",
          "Pascal",
        ],
      },
      {
        tahun: "2022 - 2023",
        link: "https://www.ruangguru.com/program/kampus-merdeka",
        title:
          "Peserta MSIB Batch 4 (Studi Independen Ruangguru - Backend Engineering)",
        desc: "Sebagai peserta MSIB Batch 4 di Ruangguru, saya mendalami spesialisasi Backend Engineering. Fokus utama saya adalah penguasaan struktur data, arsitektur data, penerapan clean code, serta pengembangan logika pemrograman menggunakan bahasa Golang.",
        detil: [
          "Arsitektur Pemrograman",
          "Fullstack Web Dev.",
          "REST API",
          "Backend Engineering",
          "Struktur Data",
          "Git",
          "Golang",
          "Tailwind CSS",
        ],
      },
      {
        tahun: "2024 - 2025",
        link: "https://karuniamultifinance.com",
        title:
          "Magang Kontrak – PT Karunia Multifinance (Fullstack Web Developer)",
        desc: "Selama 10 bulan di PT Karunia Multifinance, saya bertanggung jawab dalam pengembangan web dan IT Support. Fokus utama saya meliputi pembuatan website company profile, aplikasi rekap SLIK, serta pemeliharaan sistem pinjaman karyawan dan infrastruktur jaringan perusahaan.",
        detil: ["Jaringan Kantor", "Fullstack Web Developer", "IT Support"],
      },
      {
        tahun: "2020 - 2025",
        link: "https://dinamika.ac.id/",
        title: "S1 Sistem Informasi di Universitas Dinamika Surabaya",
        desc: "Lulusan program studi Sistem Informasi yang menggabungkan keahlian di bidang teknologi dan bisnis. Memiliki pengalaman dalam pengembangan aplikasi, analisis sistem, dan pengelolaan data untuk mendukung proses pengambilan keputusan berbasis IT.",
        detil: [
          "Struktur Data",
          "Pemrograman Lanjutan",
          "Pemrograman Android",
          "Pemrograman Web",
          "UI/UX Designer",
          "Jaringan Komputer",
          "Database Administrator",
          "Java",
          "PHP",
          "Python",
        ],
      },
      {
        tahun: "2025 - 2026",
        link: "https://www.jpayroll.com",
        title: "PT Java Consulting Indonesia (Research & Development Team)",
        desc: "Sebagai pengembang di tim R&D PT Java Consulting Indonesia, saya berfokus pada optimasi produk JPAYROLL. Tanggung jawab saya mencakup penyelesaian bugs, penanganan issues, serta pengembangan fitur custom untuk memenuhi kebutuhan spesifik pengguna.",
        detil: [
          "Fullstack Web Dev",
          "Angular JS",
          "PHP",
          "Oracle DB",
          "Bug Fixing",
        ],
      },
      {
        tahun: "2023 - Sekarang",
        link: "https://github.com/SweetSya",
        title: "Freelance Fullstack Web Developer",
        desc: "Sebagai Fullstack Developer freelance, saya merancang dan membangun solusi web secara komprehensif. Pengalaman saya mencakup pengembangan frontend dan backend untuk berbagai proyek, mulai dari company profile hingga aplikasi web kompleks yang berorientasi pada kebutuhan klien.",
        detil: [
          "Fullstack Web Dev",
          "Dokumentasi Proyek",
          "Manajemen Proyek",
          "Komunikasi Klien",
        ],
      },
    ],
    keterampilan: {
      bahasa: [
        {
          link: "/dist/assets/keterampilan/bahasa/html.png",
          name: "HTML",
        },
        {
          link: "/dist/assets/keterampilan/bahasa/css.png",
          name: "CSS",
        },
        {
          link: "/dist/assets/keterampilan/bahasa/javascript.png",
          name: "js",
        },
        {
          link: "/dist/assets/keterampilan/bahasa/java.png",
          name: "Java",
        },
        {
          link: "/dist/assets/keterampilan/bahasa/php.png",
          name: "PHP",
        },
        {
          link: "/dist/assets/keterampilan/bahasa/golang.png",
          name: "Golang",
        },
      ],
      framework: [
        {
          link: "/dist/assets/keterampilan/framework/bootstrap.png",
          name: "Bootstrap",
        },
        {
          link: "/dist/assets/keterampilan/framework/tailwind.png",
          name: "Tailwind",
        },
        {
          link: "/dist/assets/keterampilan/framework/laravel.png",
          name: "Laravel",
        },
        {
          link: "/dist/assets/keterampilan/framework/nextjs.png",
          name: "Next JS",
        },
        {
          link: "/dist/assets/keterampilan/framework/gingonic.png",
          name: "Gin-gonic",
        },
        {
          link: "/dist/assets/keterampilan/framework/vue.png",
          name: "Vue JS",
        },
        {
          link: "/dist/assets/keterampilan/framework/livewire.png",
          name: "Livewire",
        },
        {
          link: "/dist/assets/keterampilan/framework/alpine.png",
          name: "Alpine JS",
        },
      ],
      database: [
        {
          link: "/dist/assets/keterampilan/database/mysql.png",
          name: "MySQL",
        },
        {
          link: "/dist/assets/keterampilan/database/postgresql.png",
          name: "PostgreSQL",
        },
        {
          link: "/dist/assets/keterampilan/database/oracle.png",
          name: "Oracle",
        },
        {
          link: "/dist/assets/keterampilan/database/firebase.png",
          name: "Firebase",
        },
      ],
      workspace: [
        {
          link: "/dist/assets/keterampilan/workspace/git.png",
          name: "Git",
        },
        {
          link: "/dist/assets/keterampilan/workspace/vscode.png",
          name: "VSCode",
        },
      ],
    },
    proyek: [
      {
        type: "web",
        link: {
          web: "https://nusantaracert.com/",
        },
        title: "Nusantara Cert.",
        desc: "Mengembangkan website <b>nusantaracert.com</b> sebagai platform <i>company profile</i> profesional. Dilengkapi dengan sistem admin khusus untuk <b>manajemen data sertifikat</b> dan fitur <b><i>generate QR Code</i></b> secara otomatis, yang terintegrasi langsung dengan validasi sertifikat secara <i>online</i>.",
        detil: [
          "Landing & Admin Page",
          "Laravel",
          "MySQL",
          "<a href='https://github.com/mebjas/html5-qrcode' target='_blank' class='underline'>html5-qrcode&nbsp<i class='iconoir-link before:w-4 before:h-4'></i></a>",
          "<a href='https://github.com/davidshimjs/qrcodejs' target='_blank' class='underline'>QRCode.js&nbsp<i class='iconoir-link before:w-4 before:h-4'></i></a>",
        ],
        image: [
          "/dist/assets/proyek/nusantara/1.PNG",
          "/dist/assets/proyek/nusantara/2.PNG",
          "/dist/assets/proyek/nusantara/3.PNG",
        ],
      },
      {
        type: "web",
        link: {
          web: "https://zstowing.com/",
        },
        title: "ZSTowing",
        desc: "Membangun website <b>zstowing.com</b> untuk ZS Towing sebagai profil jasa towing 24 jam di Kalimantan Barat. Website responsif dan <b>dioptimasi <i>SEO</i></b>, muncul di hasil pencarian seperti <i>“towing Ketapang”</i> atau <i>“towing Kalbar”</i> untuk <b>meningkatkan jangkauan pelanggan</b>.",
        detil: [
          "Landing page",
          "Laravel",
          "Tailwind CSS",
          "<a href='https://github.com/biati-digital/glightbox' target='_blank' class='underline'>GlightBox&nbsp<i class='iconoir-link before:w-4 before:h-4'></i></a>",
          "<a href='https://github.com/michalsnik/aos' target='_blank' class='underline'>AOS&nbsp<i class='iconoir-link before:w-4 before:h-4'></i></a>",
        ],
        image: [
          "/dist/assets/proyek/zstowing/1.PNG",
          "/dist/assets/proyek/zstowing/2.PNG",
          "/dist/assets/proyek/zstowing/3.PNG",
          "/dist/assets/proyek/zstowing/4.PNG",
          "/dist/assets/proyek/zstowing/5.PNG",
        ],
      },
      {
        type: "web",
        link: {
          web: "https://demo-attendance-app.sweetsya.id/",
        },
        title: "Attendance App – Tugas Akhir (Karunia Multifinance)",
        desc: "Aplikasi presensi berbasis web (<i>PWA</i> & <i>SPA</i>) yang dilengkapi fitur <b><i>face recognition</i> (LBPH)</b> dan <b><i>geofencing</i> menggunakan algoritma <i>Haversine</i></b> untuk validasi lokasi. Mendukung <i>web push notification</i> untuk pemberitahuan <i>real-time</i> kepada karyawan.",
        detil: [
          "Tugas Akhir",
          "Laravel",
          "Tailwind CSS",
          "<a href='https://pypi.org/project/opencv-python/' target='_blank' class='underline'>OpenCV&nbsp<i class='iconoir-link before:w-4 before:h-4'></i></a>",
          "<a href='https://filamentphp.com/' target='_blank' class='underline'>FilamentPHP&nbsp<i class='iconoir-link before:w-4 before:h-4'></i></a>",
          "<a href='https://livewire.laravel.com/' target='_blank' class='underline'>Livewire&nbsp<i class='iconoir-link before:w-4 before:h-4'></i></a>",
          "<a href='https://github.com/web-push-libs/web-push-php' target='_blank' class='underline'>Web Push PHP&nbsp<i class='iconoir-link before:w-4 before:h-4'></i></a>",
          "<a href='https://leafletjs.com/' target='_blank' class='underline'>LeafletJS&nbsp<i class='iconoir-link before:w-4 before:h-4'></i></a>",
        ],
        image: [
          "/dist/assets/proyek/attendance-app/1.png",
          "/dist/assets/proyek/attendance-app/2.png",
          "/dist/assets/proyek/attendance-app/3.png",
          "/dist/assets/proyek/attendance-app/4.png",
          "/dist/assets/proyek/attendance-app/5.png",
        ],
      },
      {
        type: "web",
        link: {
          web: "https://karuniamultifinance.com/",
        },
        title: "Karunia Multifinance",
        desc: "Mengembangkan website <b>karuniamultifinance.com</b> sebagai platform <i>company profile</i> resmi. Website mendukung <b><i>multi-language</i></b> (Bahasa Indonesia & Inggris), serta dilengkapi dengan panel admin untuk <b>mengelola tampilan dan konten website</b> secara dinamis.",
        detil: [
          "Landing & Admin Page",
          "Code Igniter 4",
          "Multi Bahasa",
          "<a href='https://alpinejs.dev/' target='_blank' class='underline'>AlpineJS&nbsp<i class='iconoir-link before:w-4 before:h-4'></i></a>",
          "<a href='https://quilljs.com/' target='_blank' class='underline'>QuillJS&nbsp<i class='iconoir-link before:w-4 before:h-4'></i></a>",
        ],
        image: [
          "/dist/assets/proyek/kmf/1.png",
          "/dist/assets/proyek/kmf/2.png",
          "/dist/assets/proyek/kmf/3.png",
          "/dist/assets/proyek/kmf/4.png",
          "/dist/assets/proyek/kmf/5.png",
        ],
      },
      {
        type: "web",
        link: { web: "https://jadwal.iwash-indonesia.id/" },
        title: "iWash Indonesia - Sistem Penjadwalan",
        desc: "Mengembangkan sistem <b>penjadwalan dan administrasi</b> untuk perusahaan jasa cuci panggilan <i>(iWash Indonesia)</i>, melayani cuci sofa, kursi mobil, dan lainnya. Dilengkapi dengan fitur <b><i>push notification</i></b> berbasis web untuk notifikasi jadwal secara real-time.",
        detil: [
          "Web App & Panel Admin",
          "Laravel",
          "Bootstrap 5",
          "MySQL",
          "PHP WebPush",
          "Push Notification",
        ],
        image: [
          "/dist/assets/proyek/iwash/1.PNG",
          "/dist/assets/proyek/iwash/2.PNG",
          "/dist/assets/proyek/iwash/3.PNG",
          "/dist/assets/proyek/iwash/4.PNG",
          "/dist/assets/proyek/iwash/5.PNG",
        ],
      },
      {
        type: "web",
        link: { web: "https://borneokita.co.id/" },
        title: "Borneo Kita - Portal Berita",
        desc: "Mengembangkan <b>portal berita daerah</b> untuk wilayah Kalimantan Barat. Terdiri dari dua sistem terintegrasi: <b>borneokita.co.id</b> sebagai halaman publik pembaca berita, dan <b>portal.borneokita.co.id</b> sebagai sistem <i>back-office</i> untuk manajemen konten dan publikasi berita oleh admin.",
        detil: [
          "Multi-site (Portal & Publik)",
          "Laravel",
          "MySQL",
          "CMS / Manajemen Konten",
        ],
        image: [
          "/dist/assets/proyek/borneokita/1.PNG",
          "/dist/assets/proyek/borneokita/2.PNG",
          "/dist/assets/proyek/borneokita/3.PNG",
          "/dist/assets/proyek/borneokita/4.PNG",
          "/dist/assets/proyek/borneokita/5.PNG",
          "/dist/assets/proyek/borneokita/6.PNG",
          "/dist/assets/proyek/borneokita/7.PNG",
        ],
      },
      {
        type: "web",
        link: { web: "https://riviesbakery.id/" },
        title: "Rivies Bakery - Toko Kue Online",
        desc: "Mengembangkan website <b>pemesanan online</b> untuk <i>Rivies Bakery</i>, toko kue premium di Mojokerto. Pelanggan dapat memesan secara online dengan pilihan pembayaran melalui <b>payment gateway</b> terintegrasi maupun langsung via <b>WhatsApp</b>. Dibangun sebagai <i>Single Page Application</i> dengan tampilan modern dan responsif.",
        detil: [
          "Single Page Application (SPA)",
          "Laravel",
          "Inertia.js",
          "Vue 3",
          "Tailwind CSS",
          "Payment Gateway",
          "Integrasi WhatsApp",
        ],
        image: [
          "/dist/assets/proyek/rivies/5.PNG",
          "/dist/assets/proyek/rivies/20.PNG",
          "/dist/assets/proyek/rivies/18.PNG",
          "/dist/assets/proyek/rivies/19.PNG",
          "/dist/assets/proyek/rivies/2.PNG",
          "/dist/assets/proyek/rivies/1.PNG",
          "/dist/assets/proyek/rivies/9.PNG",
          "/dist/assets/proyek/rivies/12.PNG",
          "/dist/assets/proyek/rivies/4.PNG",
          "/dist/assets/proyek/rivies/6.PNG",
          "/dist/assets/proyek/rivies/7.PNG",
          "/dist/assets/proyek/rivies/8.PNG",
          "/dist/assets/proyek/rivies/10.PNG",
          "/dist/assets/proyek/rivies/11.PNG",
          "/dist/assets/proyek/rivies/12.PNG",
          "/dist/assets/proyek/rivies/13.PNG",
          "/dist/assets/proyek/rivies/14.PNG",
          "/dist/assets/proyek/rivies/15.PNG",
          "/dist/assets/proyek/rivies/16.PNG",
          "/dist/assets/proyek/rivies/17.PNG",
        ],
      },
      {
        type: "web",
        link: { web: "https://koniketapang.or.id/" },
        title: "KONI Ketapang - Komite Olahraga",
        desc: "Mengembangkan website resmi <b>KONI Ketapang</b> dengan konten yang sepenuhnya dinamis dan sistem admin lengkap. Fitur unggulan meliputi <b>kustomisasi tema warna</b>, sistem <b>surat-menyurat digital</b>, serta <b>penandatanganan dokumen digital</b> — dokumen PDF yang diunggah akan otomatis diberikan <i>stempel QR Code</i> yang dapat dipindai untuk verifikasi keaslian dokumen secara <i>online</i>.",
        detil: [
          "Single Page Application (SPA)",
          "Laravel",
          "Vue 3",
          "Tailwind CSS",
          "Kustomisasi Tema Dinamis",
          "Tanda Tangan Dokumen Digital",
          "Stempel & Verifikasi QR Code",
          "Sistem Surat Digital",
        ],
        image: [
          "/dist/assets/proyek/koni/1.PNG",
          "/dist/assets/proyek/koni/3.PNG",
          "/dist/assets/proyek/koni/19.PNG",
          "/dist/assets/proyek/koni/18.PNG",
          "/dist/assets/proyek/koni/8.PNG",
          "/dist/assets/proyek/koni/2.PNG",
          "/dist/assets/proyek/koni/4.PNG",
          "/dist/assets/proyek/koni/5.PNG",
          "/dist/assets/proyek/koni/6.PNG",
          "/dist/assets/proyek/koni/7.PNG",
          "/dist/assets/proyek/koni/9.PNG",
          "/dist/assets/proyek/koni/10.PNG",
          "/dist/assets/proyek/koni/11.PNG",
          "/dist/assets/proyek/koni/12.PNG",
          "/dist/assets/proyek/koni/13.PNG",
          "/dist/assets/proyek/koni/14.PNG",
          "/dist/assets/proyek/koni/15.PNG",
          "/dist/assets/proyek/koni/16.PNG",
          "/dist/assets/proyek/koni/17.PNG",
          "/dist/assets/proyek/koni/20.PNG",
          "/dist/assets/proyek/koni/21.PNG",
        ],
      },
      {
        type: "web",
        link: { web: "#" },
        title: "Sistem Baca SLIK - Karunia Multifinance",
        desc: "Mengembangkan sistem <b>pembacaan otomatis dokumen SLIK OJK</b> untuk Karunia Multifinance. Pengguna cukup mengunggah file SLIK, lalu sistem secara otomatis <b>mengekstrak dan merekap seluruh data</b> yang tersedia untuk ditampilkan sesuai kebutuhan analisis kredit. Dibangun dengan arsitektur <i>microservice</i>, menjalankan proses ekstraksi PDF berbasis Python langsung dari Laravel.",
        detil: [
          "Arsitektur Microservice",
          "Laravel",
          "Python",
          "PyMuPDF",
          "Ekstraksi & Parsing PDF",
          "Integrasi SLIK OJK",
        ],
        image: [
          "/dist/assets/proyek/slik/1.PNG",
          "/dist/assets/proyek/slik/2.PNG",
          "/dist/assets/proyek/slik/3.PNG",
        ],
      },
      {
        type: "github",
        link: {
          github: "https://github.com/SweetSya/esp32-monitoring-pc",
        },
        title: "ESP32 PC Monitoring Dashboard",
        desc: "Membangun <b>hardware monitor berbasis ESP32</b> yang menampilkan informasi <i>real-time</i> penggunaan CPU, GPU, RAM, dan suhu sistem pada layar <b>TFT kecil</b>. Perangkat berkomunikasi dengan <b>skrip Python</b> yang berjalan di PC untuk mengumpulkan data metrik sistem dan mengirimkannya ke ESP32 melalui <i>Serial</i> atau <i>Bluetooth</i>.",
        detil: [
          "Hardware Project",
          "ESP32 + TFT Display",
          "Arduino (C++)",
          "TFT_eSPI Library",
          "Python 3",
          "psutil / OpenHardwareMonitor",
          "Serial & Bluetooth",
          "Real-time Monitoring",
        ],
        image: [
          "/dist/assets/proyek/esp32monitor/1.PNG",
          "/dist/assets/proyek/esp32monitor/2.PNG",
          "/dist/assets/proyek/esp32monitor/3.PNG",
        ],
      },
    ],
  },
  en: {
    texts: {
      loading: "Loading assets..",
      welcome: "Welcome to the Portfolio,",
      explore: "Explore Now",
      subtitle: "Web Developer",
      motto: "Effort first, the results are already managed.",
      back: "Back",
      "nav-about": "About",
      "nav-experience": "Experience",
      "nav-competency": "Competency",
      "nav-project": "Projects",
      "download-cv": "Download CV",
      "scroll-down": "Scroll Down",
      "title-experience": "Experience",
      "title-competency": "Competency",
      "title-project": "Projects",
      "nav-view-all": "View All",
    },
    tentang: [
      `My journey began in <span class="text-white font-bold">2018 (High School)</span>, when a simple introduction to the Pascal language sparked my deep interest in the IT world. Through the <span class="text-white font-bold">CLUTIK</span> community, I learned that technology is not just about machine instructions, but the art of problem-solving.`,
      `Armed with that passion, I now actively develop software solutions for <span class="text-white font-bold">individuals to large-scale enterprises</span>. For me, every project is a long-term <span class="text-white font-bold"><span class="italic">problem-solving</span> game</span> that constantly motivates me to step out of my comfort zone.`,
    ],
    pengalaman: [
      {
        tahun: "2018 - 2020",
        link: "https://sman2mojokerto.sch.id/ekskul/club-tik-clutik/",
        title: "ICT Club (Clutik) at SMAN 2 Mojokerto",
        desc: "Through the CLUTIK extracurricular, I found my initial interest in IT. Here, I built a technical foundation through Pascal programming and hardware mastery, from understanding components to the computer assembly process.",
        detil: [
          "Computer Assembly",
          "Computer Operating Systems",
          "Computer Networking",
          "Basic Programming",
          "Pascal",
        ],
      },
      {
        tahun: "2022 - 2023",
        link: "https://www.ruangguru.com/program/kampus-merdeka",
        title:
          "MSIB Batch 4 Participant (Ruangguru Independent Study - Backend Engineering)",
        desc: "As an MSIB Batch 4 participant at Ruangguru, I specialized in Backend Engineering. My main focus was mastering data structures, data architecture, implementing clean code, and developing programming logic using Golang.",
        detil: [
          "Programming Architecture",
          "Fullstack Web Dev.",
          "REST API",
          "Backend Engineering",
          "Data Structures",
          "Git",
          "Golang",
          "Tailwind CSS",
        ],
      },
      {
        tahun: "2024 - 2025",
        link: "https://karuniamultifinance.com",
        title:
          "Contract Internship – PT Karunia Multifinance (Fullstack Web Developer)",
        desc: "During my 10-month contract at PT Karunia Multifinance, I was responsible for web development and IT Support. My main focus included building a company profile website, a SLIK recap application, and maintaining the employee loan system and company network infrastructure.",
        detil: ["Office Networking", "Fullstack Web Developer", "IT Support"],
      },
      {
        tahun: "2020 - 2025",
        link: "https://dinamika.ac.id/",
        title:
          "Bachelor of Information Systems at Universitas Dinamika Surabaya",
        desc: "Information Systems graduate combining expertise in technology and business. Experienced in application development, system analysis, and data management to support IT-based decision-making processes.",
        detil: [
          "Data Structures",
          "Advanced Programming",
          "Android Programming",
          "Web Programming",
          "UI/UX Designer",
          "Computer Networking",
          "Database Administrator",
          "Java",
          "PHP",
          "Python",
        ],
      },
      {
        tahun: "2025 - 2026",
        link: "https://www.jpayroll.com",
        title: "PT Java Consulting Indonesia (Research & Development Team)",
        desc: "As a developer in the R&D team at PT Java Consulting Indonesia, I focus on optimizing the JPAYROLL product. My responsibilities include bug fixing, issue handling, and developing custom features to meet specific user needs.",
        detil: [
          "Fullstack Web Dev",
          "Angular JS",
          "PHP",
          "Oracle DB",
          "Bug Fixing",
        ],
      },
      {
        tahun: "2023 - Present",
        link: "https://github.com/SweetSya",
        title: "Freelance Fullstack Web Developer",
        desc: "As a freelance Fullstack Developer, I design and build comprehensive web solutions. My experience includes frontend and backend development for various projects, ranging from company profiles to complex web applications tailored to client needs.",
        detil: [
          "Fullstack Web Dev",
          "Project Documentation",
          "Project Management",
          "Client Communication",
        ],
      },
    ],
    keterampilan: {
      bahasa: [
        { link: "/dist/assets/keterampilan/bahasa/html.png", name: "HTML" },
        { link: "/dist/assets/keterampilan/bahasa/css.png", name: "CSS" },
        {
          link: "/dist/assets/keterampilan/bahasa/javascript.png",
          name: "js",
        },
        { link: "/dist/assets/keterampilan/bahasa/java.png", name: "Java" },
        { link: "/dist/assets/keterampilan/bahasa/php.png", name: "PHP" },
        {
          link: "/dist/assets/keterampilan/bahasa/golang.png",
          name: "Golang",
        },
      ],
      framework: [
        {
          link: "/dist/assets/keterampilan/framework/bootstrap.png",
          name: "Bootstrap",
        },
        {
          link: "/dist/assets/keterampilan/framework/tailwind.png",
          name: "Tailwind",
        },
        {
          link: "/dist/assets/keterampilan/framework/laravel.png",
          name: "Laravel",
        },
        {
          link: "/dist/assets/keterampilan/framework/nextjs.png",
          name: "Next JS",
        },
        {
          link: "/dist/assets/keterampilan/framework/gingonic.png",
          name: "Gin-gonic",
        },
        {
          link: "/dist/assets/keterampilan/framework/vue.png",
          name: "Vue JS",
        },
        {
          link: "/dist/assets/keterampilan/framework/livewire.png",
          name: "Livewire",
        },
        {
          link: "/dist/assets/keterampilan/framework/alpine.png",
          name: "Alpine JS",
        },
      ],
      database: [
        {
          link: "/dist/assets/keterampilan/database/mysql.png",
          name: "MySQL",
        },
        {
          link: "/dist/assets/keterampilan/database/postgresql.png",
          name: "PostgreSQL",
        },
        {
          link: "/dist/assets/keterampilan/database/oracle.png",
          name: "Oracle",
        },
        {
          link: "/dist/assets/keterampilan/database/firebase.png",
          name: "Firebase",
        },
      ],
      workspace: [
        { link: "/dist/assets/keterampilan/workspace/git.png", name: "Git" },
        {
          link: "/dist/assets/keterampilan/workspace/vscode.png",
          name: "VSCode",
        },
      ],
    },
    proyek: [
      {
        type: "web",
        link: {
          web: "https://nusantaracert.com/",
        },
        title: "Nusantara Cert.",
        desc: "Developed the <b>nusantaracert.com</b> website as a professional <i>company profile</i> platform. Equipped with a custom admin system for <b>certificate data management</b> and an automatic <b><i>QR Code generator</i></b> feature, directly integrated with <i>online</i> certificate validation.",
        detil: [
          "Landing & Admin Page",
          "Laravel",
          "MySQL",
          "<a href='https://github.com/mebjas/html5-qrcode' target='_blank' class='underline'>html5-qrcode&nbsp<i class='iconoir-link before:w-4 before:h-4'></i></a>",
          "<a href='https://github.com/davidshimjs/qrcodejs' target='_blank' class='underline'>QRCode.js&nbsp<i class='iconoir-link before:w-4 before:h-4'></i></a>",
        ],
        image: [
          "/dist/assets/proyek/nusantara/1.PNG",
          "/dist/assets/proyek/nusantara/2.PNG",
          "/dist/assets/proyek/nusantara/3.PNG",
        ],
      },
      {
        type: "web",
        link: {
          web: "https://zstowing.com/",
        },
        title: "ZSTowing",
        desc: "Built the <b>zstowing.com</b> website for ZS Towing as a profile for a 24-hour towing service in West Kalimantan. The website is responsive and <b><i>SEO</i> optimized</b>, appearing in search results like <i>“towing Ketapang”</i> or <i>“towing Kalbar”</i> to <b>increase customer reach</b>.",
        detil: [
          "Landing page",
          "Laravel",
          "Tailwind CSS",
          "<a href='https://github.com/biati-digital/glightbox' target='_blank' class='underline'>GlightBox&nbsp<i class='iconoir-link before:w-4 before:h-4'></i></a>",
          "<a href='https://github.com/michalsnik/aos' target='_blank' class='underline'>AOS&nbsp<i class='iconoir-link before:w-4 before:h-4'></i></a>",
        ],
        image: [
          "/dist/assets/proyek/zstowing/1.PNG",
          "/dist/assets/proyek/zstowing/2.PNG",
          "/dist/assets/proyek/zstowing/3.PNG",
          "/dist/assets/proyek/zstowing/4.PNG",
          "/dist/assets/proyek/zstowing/5.PNG",
        ],
      },
      {
        type: "web",
        link: {
          web: "https://demo-attendance-app.sweetsya.id/",
        },
        title: "Attendance App – Final Project (Karunia Multifinance)",
        desc: "A web-based attendance application (<i>PWA</i> & <i>SPA</i>) equipped with a <b><i>face recognition</i> (LBPH)</b> feature and <b><i>geofencing</i> using the <i>Haversine</i> algorithm</b> for location validation. Supports <i>web push notifications</i> for <i>real-time</i> employee alerts.",
        detil: [
          "Final Project",
          "Laravel",
          "Tailwind CSS",
          "<a href='https://pypi.org/project/opencv-python/' target='_blank' class='underline'>OpenCV&nbsp<i class='iconoir-link before:w-4 before:h-4'></i></a>",
          "<a href='https://filamentphp.com/' target='_blank' class='underline'>FilamentPHP&nbsp<i class='iconoir-link before:w-4 before:h-4'></i></a>",
          "<a href='https://livewire.laravel.com/' target='_blank' class='underline'>Livewire&nbsp<i class='iconoir-link before:w-4 before:h-4'></i></a>",
          "<a href='https://github.com/web-push-libs/web-push-php' target='_blank' class='underline'>Web Push PHP&nbsp<i class='iconoir-link before:w-4 before:h-4'></i></a>",
          "<a href='https://leafletjs.com/' target='_blank' class='underline'>LeafletJS&nbsp<i class='iconoir-link before:w-4 before:h-4'></i></a>",
        ],
        image: [
          "/dist/assets/proyek/attendance-app/1.png",
          "/dist/assets/proyek/attendance-app/2.png",
          "/dist/assets/proyek/attendance-app/3.png",
          "/dist/assets/proyek/attendance-app/4.png",
          "/dist/assets/proyek/attendance-app/5.png",
          "/dist/assets/proyek/attendance-app/6.png",
        ],
      },
      {
        type: "web",
        link: {
          web: "https://karuniamultifinance.com/",
        },
        title: "Karunia Multifinance",
        desc: "Developed the <b>karuniamultifinance.com</b> website as the official <i>company profile</i> platform. The website supports <b><i>multi-language</i></b> (Indonesian & English) and is equipped with an admin panel to <b>manage the website's appearance and content</b> dynamically.",
        detil: [
          "Landing & Admin Page",
          "Code Igniter 4",
          "Multi-language",
          "<a href='https://alpinejs.dev/' target='_blank' class='underline'>AlpineJS&nbsp<i class='iconoir-link before:w-4 before:h-4'></i></a>",
          "<a href='https://quilljs.com/' target='_blank' class='underline'>QuillJS&nbsp<i class='iconoir-link before:w-4 before:h-4'></i></a>",
        ],
        image: [
          "/dist/assets/proyek/kmf/1.png",
          "/dist/assets/proyek/kmf/2.png",
          "/dist/assets/proyek/kmf/3.png",
          "/dist/assets/proyek/kmf/4.png",
          "/dist/assets/proyek/kmf/5.png",
        ],
      },
      {
        type: "web",
        link: { web: "https://jadwal.iwash-indonesia.id/" },
        title: "iWash Indonesia - Scheduling System",
        desc: "Developed a <b>scheduling and administration system</b> for an on-site cleaning service company <i>(iWash Indonesia)</i>, covering sofa, car seat, and other cleaning services. Equipped with <b><i>web push notifications</i></b> for real-time schedule alerts.",
        detil: [
          "Web App & Admin Panel",
          "Laravel",
          "Bootstrap 5",
          "MySQL",
          "PHP WebPush",
          "Push Notification",
        ],
        image: [
          "/dist/assets/proyek/iwash/1.PNG",
          "/dist/assets/proyek/iwash/2.PNG",
          "/dist/assets/proyek/iwash/3.PNG",
          "/dist/assets/proyek/iwash/4.PNG",
          "/dist/assets/proyek/iwash/5.PNG",
        ],
      },
      {
        type: "web",
        link: { web: "https://borneokita.co.id/" },
        title: "Borneo Kita - News Portal",
        desc: "Developed a <b>regional news portal</b> for West Kalimantan. Consists of two integrated systems: <b>borneokita.co.id</b> as the public-facing news reader, and <b>portal.borneokita.co.id</b> as the <i>back-office</i> system for content management and article publishing.",
        detil: [
          "Multi-site (Portal & Public)",
          "Laravel",
          "MySQL",
          "CMS / Content Management",
        ],
        image: [
          "/dist/assets/proyek/borneokita/1.PNG",
          "/dist/assets/proyek/borneokita/2.PNG",
          "/dist/assets/proyek/borneokita/3.PNG",
          "/dist/assets/proyek/borneokita/4.PNG",
          "/dist/assets/proyek/borneokita/5.PNG",
          "/dist/assets/proyek/borneokita/6.PNG",
          "/dist/assets/proyek/borneokita/7.PNG",
        ],
      },
      {
        type: "web",
        link: { web: "https://riviesbakery.id/" },
        title: "Rivies Bakery - Online Cake Store",
        desc: "Developed an <b>online ordering website</b> for <i>Rivies Bakery</i>, a premium cake shop in Mojokerto. Customers can place orders online and pay via an integrated <b>payment gateway</b> or directly through <b>WhatsApp</b>. Built as a <i>Single Page Application</i> with a modern, responsive design.",
        detil: [
          "Single Page Application (SPA)",
          "Laravel",
          "Inertia.js",
          "Vue 3",
          "Tailwind CSS",
          "Payment Gateway",
          "WhatsApp Integration",
        ],
        image: [
          "/dist/assets/proyek/rivies/5.PNG",
          "/dist/assets/proyek/rivies/20.PNG",
          "/dist/assets/proyek/rivies/18.PNG",
          "/dist/assets/proyek/rivies/19.PNG",
          "/dist/assets/proyek/rivies/2.PNG",
          "/dist/assets/proyek/rivies/1.PNG",
          "/dist/assets/proyek/rivies/9.PNG",
          "/dist/assets/proyek/rivies/12.PNG",
          "/dist/assets/proyek/rivies/4.PNG",
          "/dist/assets/proyek/rivies/6.PNG",
          "/dist/assets/proyek/rivies/7.PNG",
          "/dist/assets/proyek/rivies/8.PNG",
          "/dist/assets/proyek/rivies/10.PNG",
          "/dist/assets/proyek/rivies/11.PNG",
          "/dist/assets/proyek/rivies/12.PNG",
          "/dist/assets/proyek/rivies/13.PNG",
          "/dist/assets/proyek/rivies/14.PNG",
          "/dist/assets/proyek/rivies/15.PNG",
          "/dist/assets/proyek/rivies/16.PNG",
          "/dist/assets/proyek/rivies/17.PNG",
        ],
      },
      {
        type: "web",
        link: { web: "https://koniketapang.or.id/" },
        title: "KONI Ketapang - Sports Committee",
        desc: "Developed the official website for <b>KONI Ketapang</b> (National Sports Committee) with fully dynamic content and a complete admin system. Key features include <b>color theme customization</b>, a <b>digital correspondence system</b>, and <b>digital document signing</b> — uploaded PDFs are automatically stamped with a <i>QR Code</i> that can be scanned to verify document authenticity <i>online</i>.",
        detil: [
          "Single Page Application (SPA)",
          "Laravel",
          "Vue 3",
          "Tailwind CSS",
          "Dynamic Theme Customization",
          "Digital Document Signing",
          "QR Code Stamp & Verification",
          "Digital Correspondence System",
        ],
        image: [
          "/dist/assets/proyek/koni/1.PNG",
          "/dist/assets/proyek/koni/3.PNG",
          "/dist/assets/proyek/koni/19.PNG",
          "/dist/assets/proyek/koni/18.PNG",
          "/dist/assets/proyek/koni/8.PNG",
          "/dist/assets/proyek/koni/2.PNG",
          "/dist/assets/proyek/koni/4.PNG",
          "/dist/assets/proyek/koni/5.PNG",
          "/dist/assets/proyek/koni/6.PNG",
          "/dist/assets/proyek/koni/7.PNG",
          "/dist/assets/proyek/koni/9.PNG",
          "/dist/assets/proyek/koni/10.PNG",
          "/dist/assets/proyek/koni/11.PNG",
          "/dist/assets/proyek/koni/12.PNG",
          "/dist/assets/proyek/koni/13.PNG",
          "/dist/assets/proyek/koni/14.PNG",
          "/dist/assets/proyek/koni/15.PNG",
          "/dist/assets/proyek/koni/16.PNG",
          "/dist/assets/proyek/koni/17.PNG",
          "/dist/assets/proyek/koni/20.PNG",
          "/dist/assets/proyek/koni/21.PNG",
        ],
      },
      {
        type: "web",
        link: { web: "#" },
        title: "SLIK Reader - Karunia Multifinance",
        desc: "Developed an <b>automated SLIK OJK document reader</b> for Karunia Multifinance. Users simply upload a SLIK file, and the system automatically <b>extracts and summarizes all data</b> for credit analysis needs. Built with a <i>microservice</i> architecture, running a Python-based PDF extraction process directly from Laravel.",
        detil: [
          "Microservice Architecture",
          "Laravel",
          "Python",
          "PyMuPDF",
          "PDF Extraction & Parsing",
          "OJK SLIK Integration",
        ],
        image: [
          "/dist/assets/proyek/slik/1.PNG",
          "/dist/assets/proyek/slik/2.PNG",
          "/dist/assets/proyek/slik/3.PNG",
        ],
      },
      {
        type: "github",
        link: {
          github: "https://github.com/SweetSya/esp32-monitoring-pc",
        },
        title: "ESP32 PC Monitoring Dashboard",
        desc: "Built an <b>ESP32-based hardware monitor</b> that displays <i>real-time</i> CPU, GPU, RAM usage, and system temperatures on a small <b>TFT screen</b>. The device communicates with a companion <b>Python script</b> running on the PC, which collects system metrics and sends them to the ESP32 via <i>Serial</i> or <i>Bluetooth</i>.",
        detil: [
          "Hardware Project",
          "ESP32 + TFT Display",
          "Arduino (C++)",
          "TFT_eSPI Library",
          "Python 3",
          "psutil / OpenHardwareMonitor",
          "Serial & Bluetooth",
          "Real-time Monitoring",
        ],
        image: [
          "/dist/assets/proyek/esp32monitor/1.PNG",
          "/dist/assets/proyek/esp32monitor/2.PNG",
          "/dist/assets/proyek/esp32monitor/3.PNG",
        ],
      },
    ],
  },
};

export { main };
